apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  rootPassword: {{ .Values.db.rootPassword }}
  database: {{ .Values.db.database }}
  user: {{ .Values.db.user }}
  password: {{ .Values.db.password }}

